---
title: "Yifei Zhao's Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
library(stringr)
```

```{r include = FALSE}
data("rest_inspec")
set.seed(12345)
data =  sample_n(rest_inspec, 1000) %>% 
  janitor::clean_names() %>% 
  mutate(cuisine_description = str_sub(cuisine_description, start = 1, end = 10)) %>% 
  drop_na(score)
```

fig <- plot_ly(data, x = ~Bodywt, y = ~Brainwt, type = 'scatter',
        mode = 'text', text = ~Primates, textposition = 'middle right',
        textfont = list(color = '#000000', size = 16))
fig <- fig %>% layout(title = 'Primates Brain and Body Weight',
         xaxis = list(title = 'Body Weight (kg)',
                      zeroline = TRUE,
                      range = c(0, 250)),
         yaxis = list(title = 'Brain Weight (g)',
                      range = c(0,1400)))

fig

### Histogram
```{r echo = FALSE}
fig1 = plot_ly(data, x = ~score, color = ~cuisine_description, type = 'histogram') %>% 
  layout(title = 'score distribution by cuisine_description')
fig1
```

### Boxplot
```{r echo = FALSE}
fig2 = plot_ly(data, y = ~score, color = ~boro, type = 'box') %>% 
  layout(title = 'score distribution by boro')
fig2
```

### Pieplot
```{r echo = FALSE}
fig3 = plot_ly(data, labels = ~critical_flag, type = 'pie') %>% 
    layout(title = 'critical_flag proportion')
fig3
```
